### ISSUE TITLE
Dépendance yaml nécessaire ?

### ISSUE THREAD

**Issue by laem** [EmileRolley/publiopti#2]
https://github.com/EmileRolley/publiopti/blob/14d8078c704e222902d0808f70bc5ffd5cecbbcc/package.json#L21

@EmileRolley 

Je demande car il ne faudrait pas devoir importer cette grosse lib côté client pour nosgestesclimat.

**Comment by EmileRolley** [comment]
La dépendance n'est pas nécessaire et est supprimée à présent :+1:
