### ISSUE TITLE
Problème du au remplacement des règles par regexp ? 

### ISSUE THREAD

**Issue by laem** [EmileRolley/publiopti#3]
@EmileRolley j'ai l'impression que ce problème viendrait du remplacement actuellement un peu trop artisanal dont on avait parlé. La règle chocolat chaud disparait, et la question mosaïque plante alors à l'affichage. 

![image](https://user-images.githubusercontent.com/1177762/215535722-09d9bdb2-b450-4d02-9177-ef0c6024fbdf.png)

**Comment by EmileRolley** [comment]
Hmm.. Dans la version compressée la règle `chocolat chaud` est compressée à `0` donc même si c'est une erreur dans l'optimisation, le problème de la mosaïque est causé par autre chose je pense.

**Comment by laem** [comment]
Oui du coup la question est pourquoi cette variable `chocolat chaud` qui pourtant comporte une question est compressée à 0. 

![image](https://user-images.githubusercontent.com/1177762/215752848-00c73bfc-ecdb-4306-835a-0c403fff1cb9.png)

**Comment by EmileRolley** [comment]
Fixed by https://github.com/EmileRolley/publiopti/commit/48ae4a788b01b85d1fbb29797f464f4c5fb6ea5

+ Switch to `publicodes@1.0.0-beta.66`
+ Add a unit test for the case when `par défaut = 0`
